//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HenrysBookstore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HENRYEntities : DbContext
    {
        public HENRYEntities()
            : base("name=HENRYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<BRANCH> BRANCHes { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<PUBLISHER> PUBLISHERs { get; set; }
        public virtual DbSet<WROTE> WROTEs { get; set; }
        public virtual DbSet<inventory_branch> inventory_branch { get; set; }
        public virtual DbSet<noStock2> noStock2 { get; set; }
        public virtual DbSet<vBookDetail> vBookDetails { get; set; }
        public virtual DbSet<vBookInventory> vBookInventories { get; set; }
    }
}
