//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HenrysBookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class noStock2
    {
        public string title { get; set; }
        public string book_code { get; set; }
    }
}
