//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HenrysBookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBookDetail
    {
        public string AUTHOR_LAST { get; set; }
        public string AUTHOR_FIRST { get; set; }
        public string TITLE { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PAPERBACK { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string PUBLISHER_NAME { get; set; }
        public string BOOK_CODE { get; set; }
        public string PUBLISHER_CODE { get; set; }
        public int AUTHOR_NUM { get; set; }
    }
}
